# Generated by Django 4.2.1 on 2023-05-03 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackr', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trackentry',
            options={'verbose_name': 'Track Entry', 'verbose_name_plural': 'Track Entries'},
        ),
    ]
